<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Account\**" />
    <EmbeddedResource Remove="Account\**" />
    <None Remove="Account\**" />
  </ItemGroup>

</Project>
